import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setupDom} from '../../genro-dom-js/tests/dom.js';
setupDom();
const {fromTytx} = await import('genro-tytx');
const {Bag} = await import('genro-bag-js');
const {mountInspector} = await import('../src/genro_pages/resources/inspector.js');
const host = document.createElement('div');
document.body.append(host);
const data = new Bag();
data.setItem('title', 'Original');
const source = new Bag();
source.setItem('node', 'Text');
const tool = mountInspector(host, fromTytx(readFileSync(0, 'utf8'), 'json'), {builder:{data, source}});
assert.equal(host.querySelector('gnr-storetree').storeBag, data);
const key = extra => document.dispatchEvent(new window.KeyboardEvent('keydown', {
    key:'D', ctrlKey:true, shiftKey:true, bubbles:true, cancelable:true, ...extra}));
key({altKey:true});
assert.equal(tool.app.builder.data.getItem('opened'), false);
key();
assert.equal(tool.app.builder.data.getItem('opened'), true);
assert.equal(host.querySelector('gnr-storetree').storeBag, data);
host.querySelector('gnr-storetree').shadowRoot.querySelector('.leaf').click();
assert.match(host.querySelector('[data-inspector="data-detail"]').textContent, /Original/);
data.setItem('title', 'Changed');
assert.match(host.querySelector('[data-inspector="data-detail"]').textContent, /Changed/);
key({repeat:true});
assert.equal(tool.app.builder.data.getItem('opened'), true);
key();
assert.equal(tool.app.builder.data.getItem('opened'), false);
tool.dispose();
key();
assert.equal(tool.app.builder.data.getItem('opened'), false);
console.log('Inspector: Python recipe, real Bag, selection, updates, shortcut and disposal passed.');
